name: frost
env_file:
  - .env
recipe: platformsh

config:
  webroot: docroot
  xdebug: true
  overrides:
    app:
      runtime:
        extensions:
          - xdebug

services:
  app:
    xdebug: "debug,develop"
    overrides:
      environment:
        # Support debugging Drush with XDEBUG.
        # @see https://docs.lando.dev/guides/lando-phpstorm.html
        PHP_IDE_CONFIG: "serverName=appserver"
        DRUSH_OPTIONS_URI: "https://www.frost.lndo.site/"
        SERVER_NAME: "default"
        HTTP_HOST: "default"
  chrome:
    type: compose
    services:
      image: isholgueras/chrome-headless:latest
      # Lando always overrides the default entrypoint.
      command: chromedriver --verbose --whitelisted-ips=
    portforward: 9222

tooling:
  behat:
    service: app
    description: Run behat tests
    cmd: /app/vendor/bin/behat
  blt:
    service: app
    description: Quickly run BLT from container context
    cmd: /app/vendor/bin/blt
  drush:
    cmd: "/app/vendor/bin/drush --root=/app/docroot --uri=https://www.frost.lndo.site"
