name: frost
env_file:
  - .env
recipe: platformsh

config:
  webroot: web
  xdebug: true
  overrides:
    app:
      runtime:
        extensions:
          - xdebug

services:
  app:
    xdebug: "debug,develop"
    overrides:
      environment:
        # Support debugging Drush with XDEBUG.
        # @see https://docs.lando.dev/guides/lando-phpstorm.html
        PHP_IDE_CONFIG: "serverName=appserver"

tooling:
  behat:
    service: app
    description: Run behat tests
    cmd: /app/vendor/bin/behat
  drush:
    cmd: "/app/vendor/bin/drush --root=/app/web --uri=https://www.frost.lndo.site"
