name: frost
env_file:
  - .env
recipe: platformsh

config:
  webroot: web
  xdebug: true

tooling:
  behat:
    service: app
    description: Run behat tests
    cmd: /app/vendor/bin/behat
  drush:
    cmd: "/app/vendor/bin/drush --root=/app/web --uri=https://www.frost.lndo.site"
